apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: airflow-metrics
  namespace: monitoring
  labels:
    release: prometheus-stack
    team: data-lake
spec:
  selector:
    matchLabels:
      app: airflow
  namespaceSelector:
    matchNames:
      - airflow
  endpoints:
    - port: web
      path: /metrics
      interval: 30s

