apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-web
  namespace: airflow
spec:
  template:
    spec:
      volumes:
        - name: airflow-dags
          configMap:
            name: airflow-dags
      containers:
        - name: web
          volumeMounts:
            - name: airflow-dags
              mountPath: /opt/airflow/dags
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-scheduler
  namespace: airflow
spec:
  template:
    spec:
      volumes:
        - name: airflow-dags
          configMap:
            name: airflow-dags
      containers:
        - name: scheduler
          volumeMounts:
            - name: airflow-dags
              mountPath: /opt/airflow/dags
