# Lightweight setup for MicroK8s / Multipass
grafana:
  enabled: false   # You already have Grafana
alertmanager:
  enabled: false

prometheus:
  prometheusSpec:
    serviceMonitorSelector:
      matchLabels:
        team: data-lake
    resources:
      requests:
        cpu: 200m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
  service:
    type: ClusterIP

# Enable CRDs (for first time)
global:
  rbac:
    create: true
