coordinator:
  replicaCount: 1
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
worker:
  replicaCount: 1
  resources:
    requests:
      cpu: 200m
      memory: 512Mi

catalogs:
  - name: hive
    type: hive
    config: |
      connector.name=hive-hadoop2
      hive.s3.aws-access-key=demoaccess
      hive.s3.aws-secret-key=demosecretkey
      hive.s3.endpoint=http://demo-minio.minio.svc.cluster.local:9000
      hive.s3.path-style-access=true
      hive.non-managed-table-writes-enabled=true
      hive.s3.ssl.enabled=false
