apiVersion: apps/v1
kind: Deployment
metadata:
  name: bankapp
  namespace: devproject
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: bankapp
  template:
    metadata:
      labels:
        app: bankapp
    spec:
      containers:
        - name: bankapp
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          envFrom:
            - secretRef:
                name: bankapp-db-externalsecret
          ports:
            - containerPort: 8080
