apiVersion: apps/v1
kind: Deployment
metadata:
  name: bankapp
  namespace: devproject
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: bankapp
  template:
    metadata:
      labels:
        app: bankapp
    spec:
      containers:
        - name: bankapp
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
            - name: MYSQL_HOST
              value: mysql-service
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: bankapp-db-externalsecret
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bankapp-db-externalsecret
                  key: password
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: bankapp-db-externalsecret
                  key: database
          ports:
            - containerPort: 8080
