apiVersion: v1
kind: Service
metadata:
  name: bankapp-service
  namespace: devproject
spec:
  selector:
    app: bankapp
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
  type: {{ .Values.service.type }}
