replicaCount: 1
persistence:
  enabled: false

adminUser: admin
adminPassword: admin

service:
  type: ClusterIP
  port: 3000

resources:
  requests:
    cpu: 100m
    memory: 256Mi
    
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards
dashboardsConfigMaps:
  default: grafana-dashboard-trino
